# Generated by Django 3.2.6 on 2022-10-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='slot_time',
            field=models.CharField(default='Morning', max_length=100),
        ),
    ]
