# Generated by Django 3.2.6 on 2022-10-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_bookings_slot_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('issue_type', models.CharField(default='Feedback', max_length=100)),
                ('client_data', models.CharField(max_length=100)),
                ('issue', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='bookings',
            name='slot',
            field=models.IntegerField(default=0),
        ),
    ]
